### PR TITLE
feat: inline comments

### PR DESCRIPTION
**Pull request by lucasfcnunes**
Answers https://github.com/jonhadfield/python-hosts/issues/20
Retries https://github.com/jonhadfield/python-hosts/pull/10

Sorry ;) https://github.com/jonhadfield/python-hosts/pull/35#issuecomment-860255683

### CODE REVIEW

**Comment by lucasfcnunes** [comment]
making more changes to this.
now i'm running the actual tests and making some too haha

**Comment by lucasfcnunes** [comment]
@jonhadfield, any thoughts on this?

**Comment by jonhadfield** [comment]
Sorry it got closed. I'll take a look asap.

**Comment by sebalis** [comment]
Hi @jonhadfield, the PR seems to have been automatically closed a second time before you got to merge it. Could you reopen and merge? I’m intertested in using this feature, and also I’d consider it important to add coverage for this part of the hosts file format. I was able to merge it in a clone (on my local system, not on Github) without conflicts and all tests succeeded. Thanks :-)

**Comment by sebalis** [comment]
Oh, and while you’re at it, Id suggest editing the commits to remove the misspelling of the past participle of “split” that was introduced by @lucasfcnunes – which should of course (and confusingly) be “split” but was coded as “splited”.

**Pull request merged**
